kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: s3-acq-granule-cache
  namespace: processing
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: ceph-fs
