# Copyright 2023 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-sl1-tasktablexslt
  namespace: processing

data:
  tasktable.xslt: |
    <?xml version="1.0" encoding="UTF-8"?>
    <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
      
      <xsl:output version="1.0" method="xml" omit-xml-declaration="no"
        standalone="yes" indent="yes" />

      <xsl:template match="List_of_Dyn_ProcParams">
        <List_of_Dyn_ProcParam>
          <xsl:apply-templates select="@*|node()"/>
        </List_of_Dyn_ProcParam>
      </xsl:template>

      <xsl:template match="Cfg_File">
        <Cfg_Files>
          <xsl:apply-templates select="@*|node()"/>
        </Cfg_Files>
      </xsl:template>

      <xsl:template match="Output/File_Type">
        <Type>
          <xsl:apply-templates select="@*|node()"/>
        </Type>
      </xsl:template>

      <!-- Copy Template -->
      <xsl:template match="@*|node()">
        <xsl:copy>
          <xsl:apply-templates select="@*|node()" />
        </xsl:copy>
      </xsl:template>

    </xsl:stylesheet>