apiVersion: v1
kind: Secret
type: Opaque
data:
  USERNAME: "{{ xbip.mti.username | b64encode }}"
  PASSWORD: "{{ xbip.mti.password | b64encode }}"
  CLIENT_ID: "{{ cadip.mti.clientid | b64encode }}"
  CLIENT_SECRET: "{{ cadip.mti.clientsecret | b64encode }}" 
metadata:
  name: cadipmti
  namespace: processing
