apiVersion: v1
kind: Secret
type: Opaque
data:
  USERNAME: "{{ xbip.nsg.username | b64encode }}"
  PASSWORD: "{{ xbip.nsg.password | b64encode }}"
  CLIENT_ID: "{{ cadip.nsg.clientid | b64encode }}"
  CLIENT_SECRET: "{{ cadip.nsg.clientsecret | b64encode }}" 
metadata:
  name: cadipnsg
  namespace: processing
