
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/instance: s2-l1c
    scaledobject.keda.sh/name: s2-l1c
  name: s2-l1c
  namespace: processing
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          deployment
    name:          s2-l1-part3-ew-l1c-v1
    envSourceContainerName: s2-l1-part3-ew-l1c-v1

  pollingInterval:  30
  cooldownPeriod:   2500
  minReplicaCount:  0
  maxReplicaCount:  15
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 2500
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: prometheus
      metadata:
        # Required fields:
        serverAddress: http://thanos-query.monitoring.svc.cluster.local:9090
        metricName: "kafka_consumergroup_lag" 
        query: sum(kafka_consumergroup_lag{consumergroup=~"s2-l1-ew-l1c.*",topic=~".*s2-l1-part3.pw-l1c.*"}>=0)
        threshold: '2'
        activationThreshold: '0' 
