apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: elasticsearch-processing-traces
  labels:
    app.kubernetes.io/instance: elasticsearch-processing
spec:
  name: elasticsearch-processing-traces
  datasources:
  - name: ES-traces
    type: elasticsearch
    access: Server
    database: processing_trace*
    url: http://elasticsearch-processing-es-coordinating.database.svc.cluster.local:9200
    version: 1
    isDefault: false
    editable: true
    jsonData:
      esVersion: 7.15.2
      logMessageField: message
      logLevelField: level
      timeField: "@timestamp"
      tlsSkipVerify: true
