kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: s2-dem
  namespace: processing
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-fs
