apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/instance: s2-l0c
    scaledobject.keda.sh/name: s2-l0C
  name: s2-l0c
  namespace: processing
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          deployment
    name:          s2-l0c-part2-ew-l0c-v1
    envSourceContainerName: s2-l0c-part2-ew-l0c-v1
  pollingInterval:  30
  cooldownPeriod:   7200
  minReplicaCount:  0
  maxReplicaCount:  1
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 3600
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: prometheus
      metadata:
        # Required fields:
        serverAddress: http://thanos-query.monitoring.svc.cluster.local:9090
        metricName: "kafka_consumergroup_lag" 
        query: sum(kafka_consumergroup_lag{consumergroup=~"s2-l0c-ew.*",topic=~".*s2-l0c-part2.*pw-l0c.*"}>=0)
        threshold: '1'
        activationThreshold: '0' 
