apiVersion: v1
kind: Secret
type: Opaque
data:
  USERNAME: "{{ xbip.ins.username | b64encode }}"
  PASSWORD: "{{ xbip.ins.password | b64encode }}"
  CLIENT_ID: "{{ cadip.ins.clientid | b64encode }}"
  CLIENT_SECRET: "{{ cadip.ins.clientsecret | b64encode }}" 
metadata:
  name: cadipins
  namespace: processing
