kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: s2-l0-shared
  namespace: processing
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: ceph-fs
