apiVersion: v1
kind: Secret
type: Opaque
data:
  mongo.password: "{{ s2.mongodb.password | b64encode }}"
  mongo.username: "{{ s2.mongodb.username | b64encode }}"
  obs.accessKey: "{{ s3.access_key | b64encode }}"
  obs.secretKey: "{{ s3.secret_key | b64encode }}"
metadata:
  name: s2-l0u-pw
  namespace: processing

---

apiVersion: v1
kind: Secret
type: Opaque
data:
  obs.accessKey: "{{ s3.access_key | b64encode }}"
  obs.secretKey: "{{ s3.secret_key | b64encode }}"
metadata:
  name: s2-l0u-ew
  namespace: processing
