commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"

namespace: processing

helmCharts:
- name: rs-user-web-client
  repo: http://artifactory.coprs.esa-copernicus.eu/artifactory/rs-helm
  version: 1.9.0
  valuesFile: values.yaml
  releaseName: "{{ app_name }}"
  namespace: processing
