apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/instance: s1-l0asp-high
    scaledobject.keda.sh/name: s1-l0asp-high
  name: s1-l0asp-high
  namespace: processing
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          deployment
    name:          s1-l0asp-part1-execution-worker-high-v1
    envSourceContainerName: s1-l0asp-part1-execution-worker-high-v1
  pollingInterval:  30
  cooldownPeriod:   3600
  minReplicaCount:  0
  maxReplicaCount:  2
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 3600
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: prometheus
      metadata:
        # Required fields:
        serverAddress: http://thanos-query.monitoring.svc.cluster.local:9090
        metricName: "kafka_consumergroup_lag" 
        query: sum(kafka_consumergroup_lag{consumergroup=~"s1-l0asp-.*",topic=~".*priority-filter-high.*"} >=0)
        threshold: '1'
        activationThreshold: '0' 

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/instance: s1-l0asp-medium
    scaledobject.keda.sh/name: s1-l0asp-medium
  name: s1-l0asp-medium
  namespace: processing
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          deployment
    name:          s1-l0asp-part2-execution-worker-medium-v1
    envSourceContainerName: s1-l0asp-part2-execution-worker-medium-v1
  pollingInterval:  30
  cooldownPeriod:   3600
  minReplicaCount:  0
  maxReplicaCount:  2
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 3600
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: prometheus
      metadata:
        # Required fields:
        serverAddress: http://thanos-query.monitoring.svc.cluster.local:9090
        metricName: "kafka_consumergroup_lag" 
        query: sum(kafka_consumergroup_lag{consumergroup=~"s1-l0asp-.*",topic="s1-l0asp-part2.priority-filter-medium"} >=0)
        threshold: '1'
        activationThreshold: '0'

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/instance: s1-l0asp-low
    scaledobject.keda.sh/name: s1-l0asp-low
  name: s1-l0asp-low
  namespace: processing
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          deployment
    name:          s1-l0asp-part3-execution-worker-low-v1
    envSourceContainerName: s1-l0asp-part3-execution-worker-low-v1
  pollingInterval:  30
  cooldownPeriod:   3600
  minReplicaCount:  0
  maxReplicaCount:  2
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 3600
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: prometheus
      metadata:
        # Required fields:
        serverAddress: http://thanos-query.monitoring.svc.cluster.local:9090
        metricName: "kafka_consumergroup_lag" 
        query: sum(kafka_consumergroup_lag{consumergroup=~"s1-l0asp-.*",topic="s1-l0asp-part3.priority-filter-low"} >=0)
        threshold: '1'
        activationThreshold: '0' 
