apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/instance: s1-l0aiop
    scaledobject.keda.sh/name: s1-l0aiop
  name: s1-l0aiop
  namespace: processing
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          deployment
    name:          s1-l0aiop-part1-execution-worker-v1
    envSourceContainerName: s1-l0aiop-part1-execution-worker-v1
  pollingInterval:  30
  cooldownPeriod:   1800
  minReplicaCount:  0
  maxReplicaCount:  1
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 900
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 120
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: prometheus
      metadata:
        # Required fields:
        serverAddress: http://thanos-query.monitoring.svc.cluster.local:9090
        metricName: "kafka_consumergroup_lag" 
        query: sum(kafka_consumergroup_lag{consumergroup=~"s1-l0aiop-.*",topic=~".*preparation-worker.*"}>=0)
        threshold: '1'
        activationThreshold: '0' 
