apiVersion: v1
kind: Secret
type: Opaque
data:
  USERNAME: "{{ edip.pedc.username | b64encode }}"
  PASSWORD: "{{ edip.pedc.password | b64encode }}"
metadata:
  name: edippedc
  namespace: processing

---

apiVersion: v1
kind: Secret
type: Opaque
data:
  USERNAME: "{{ edip.bedc.username | b64encode }}"
  PASSWORD: "{{ edip.bedc.password | b64encode }}"
metadata:
  name: edipbedc
  namespace: processing

