apiVersion: v1
kind: Secret
type: Opaque
data:
  USERNAME: "{{ xbip.mps.username | b64encode }}"
  PASSWORD: "{{ xbip.mps.password | b64encode }}"
  CLIENT_ID: "{{ cadip.mps.clientid | b64encode }}"
  CLIENT_SECRET: "{{ cadip.mps.clientsecret | b64encode }}"
  AUTHORIZATION: "{{ cadip.mps.authorization | b64encode }}" 
metadata:
  name: cadipmps
  namespace: processing
