apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/instance: s3-sl2-nrt
    scaledobject.keda.sh/name: s3-sl2-nrt
  name: s3-sl2-nrt
  namespace: processing
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          deployment
    name:          s3-sl2-nrt-part1-execution-worker-v1
    envSourceContainerName: s3-sl2-nrt-part1-execution-worker-v1
  pollingInterval:  30
  cooldownPeriod:   1200
  minReplicaCount:  0
  maxReplicaCount:  2
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 1200
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: prometheus
      metadata:
        # Required fields:
        serverAddress: http://thanos-query.monitoring.svc.cluster.local:9090
        metricName: "kafka_consumergroup_lag" 
        query: sum(kafka_consumergroup_lag{consumergroup=~"s3-sl2-nrt-part1.*",topic=~".*s3-sl2-nrt-part1.*preparation.*"}>=0)
        threshold: '2'
        activationThreshold: '0' 
