apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: elasticsearch-processing-index-l0acn
  labels:
    app.kubernetes.io/instance: elasticsearch-processing
spec:
  name: elasticsearch-processing-index-l0acn.yaml
  datasources:
    - name: elasticsearch-l0acn
      type: elasticsearch
      access: Server
      database: "l0_acn"
      url: http://elasticsearch-processing-es-coordinating.database.svc.cluster.local:9200
      isDefault: false
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeField: "insertionTime"
        esVersion: 7.15.2
        logMessageField: "productName"
