apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: elasticsearch-processing-index-prip
  labels:
    app.kubernetes.io/instance: elasticsearch-processing
spec:
  name: elasticsearch-processing-index-prip.yaml
  datasources:
    - name: elasticsearch-prip
      type: elasticsearch
      access: Server
      database: "prip"
      url: http://elasticsearch-processing-es-coordinating.database.svc.cluster.local:9200
      isDefault: false
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeField: "creationDate"
        esVersion: 7.15.2
        logMessageField: "name"
