apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: elasticsearch-processing-index-aux-mpl-msk
  labels:
    app.kubernetes.io/instance: elasticsearch-processing
spec:
  name: elasticsearch-processing-index-aux_mpl_msk.yaml
  datasources:
  - name: ES aux,mpl,msk
    type: elasticsearch
    access: Server
    database: aux*,mpl*,msk*
    url: http://elasticsearch-processing-es-coordinating.database.svc.cluster.local:9200
    isDefault: false
    editable: true
    version: 1
    jsonData:
      esVersion: 7.15.2
      logMessageField: productName
      timeField: insertionTime
      tlsSkipVerify: true   
