on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  
jobs:
  backup:
    runs-on: ubuntu-latest
    environment: backup
    strategy:
      matrix:
        repository: [infrastructure, processing-sentinel-1, processing-sentinel-2, processing-sentinel-3, production-common, reference-system-documentation, reference-system-software, rs-config, rs-issues, user-web-client, website]
    steps:
    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.1
      with:
        access_key: ${{ secrets.ACCESS_KEY_ID }}
        secret_key: ${{ secrets.SECRET_ACCESS_KEY }}

    - name: Interact with object storage
      run: |
        LIST2DELDAILY=$(s3cmd --host=${{ secrets.HOST_BASE }} --host-bucket=${{ secrets.HOST_BUCKET }} ls s3://csc-rs-backup/COPRS/${{ matrix.repository }}/ | grep DAILY | cut -d '/' -f 5,6 | sort -t '/' -k 2 | head -n -15) ;
        for BACKUP in ${LIST2DELDAILY} ; do s3cmd --host=${{ secrets.HOST_BASE }} --host-bucket=${{ secrets.HOST_BUCKET }} ls ${BACKUP} ; done ;
        LIST2DELMONTHLY=$(s3cmd --host=${{ secrets.HOST_BASE }} --host-bucket=${{ secrets.HOST_BUCKET }} ls s3://csc-rs-backup/COPRS/${{ matrix.repository }}/ | grep MONTHLY | cut -d '/' -f 5,6 | sort -t '/' -k 2 | head -n -2) ;
        for BACKUP in ${LIST2DELMONTHLY} ; do s3cmd --host=${{ secrets.HOST_BASE }} --host-bucket=${{ secrets.HOST_BUCKET }} ls ${BACKUP} ; done ;
