name: Java Maven CI

on: [push]

env:
  ARTIFACTORY_BASE_URL: "artifactory.coprs.esa-copernicus.eu" # TODO: Set as env variable
  ARTIFACTORY_PROJECT: "abc-maven"
  USERNAME: ${{ secrets.ARTIFACTORY_USER }}
  PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned

      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: run test
        run: chmod +x run-test.sh && ./run-test.sh

      - name: sonarqube scan 
        run: mvn sonar:sonar -Dsonar.projectKey=${{github.repository}} -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} -Dsonar.branch.name=${{ env.GIT_BRANCH }}

      - name: Build jar 
        run: mvn clean install 
      
      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v11
        with:
          servers: '[{"id": "dummy-id","username": "${{ env.USERNAME }}", "password": "${{ env.PASSWORD }}"}]'

      # - name: Push to Artifactory
      #   run: mvn jar:jar deploy:deploy -Dfile=target/*.jar -DrepositoryId=dummy-id -DpomFile=pom.xml -DaltDeploymentRepository=dummy-id::default::https://${{ env.ARTIFACTORY_BASE_URL }}/artifactory/${{ env.ARTIFACTORY_PROJECT }}
